### ISSUE TITLE
Aldoni pliajn lingvojn por StarDict kaj/aŭ XDXF

### ISSUE THREAD

**Issue by wdiestel** [revuloj/voko-formiko#10]
Vâspuhr:

> Mi interesiĝas pri Hindeŭropaj lingvoj (precipe : Hispana, Germana,  
> Franca, Itala, Portugala, Latina, Greka, Sveda, Norvega, Hinda, Sanskrita,  
> Dana, Angla, Albana, Armena, Bretona, Bulgara, Galega, Irlanda, Islanda,  
> Kataluna, Kurda, Latva, Litova, Malnovgreka, Nederlanda, Oseta, Paŝtua,  
> Persa, Pola, Rumana, Rusa, Skotgaela, Slovaka, Taĝika, Ukraina) kaj  
> artefaritaj lingvoj (Ida, Interlingvaa, Volapuka)

El tiuj la sekvaj havas pli ol 1000 tradukoj en Revo:
Franca, Itala, Portugala, Latina, Greka, Sveda, Angla, Bretona, Bulgara, Kataluna, Nederlanda,
Persa, Pola, Rumana, Rusa, Slovaka

**Comment by wdiestel** [comment]
Pri XDXF-formato vd. https://en.wikipedia.org/wiki/XDXF, resp. https://github.com/soshial/xdxf_makedict/blob/master/format_standard/xdxf_description.md

Tradukojn oni povus aldoni per pliaj `<k>` aŭ per `<dtrn>`. La dua ests verŝajne la pli ĝusta maniero, sed ni devos eltrovi, ĉu la serĉado tiel bone funkcias.

**Comment by reta-vortaro** [comment]
Aldonita nun al XDXF kiel `<dtrn>`, transformkodo en XSL jam ekzistis, sed ne funkciis pro malĝusta XPath...
eldono: https://github.com/revuloj/revo-fonto/releases/tag/v2020-08-31-dictd-xdxf
